// Generated by https://quicktype.io
export interface PokemonPaginateRespon {
    count:    number;
    next:     string;
    previous: null;
    results:  Result[];
}

export interface Result {
    name: string;
    url:  string;
}
export interface OnePokemon {
    id: string;
    name: string;
    imgUrl:  string;
    color?: string;
}
